name: DFS CI

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout repo
      - uses: actions/setup-go@v5
        name: Setup Go
        with:
          go-version: '>=1.23.0'
      - run: go version
      - run: make test
        name: Run all tests